### PR TITLE
Use None rather than Empty list

### PR DESCRIPTION
**Pull request by marcfiu**
## 📝 Description
Another untested case for firewall updates yielded improper handling of rules that had either no ipv4 or ipv6 addresses. The code would default to an empty list, while the API wants None in that case.

**What does this PR do and why is this change necessary?**

Default to None to represent an empty IPvX list in rules.

## ✔️ How to Test

**What are the steps to reproduce the issue or verify the changes?**

**How do I run the relevant unit/integration tests?**

use included firewall_update/main.yaml test

## 📷 Preview

**If applicable, include a screenshot or code snippet of this change. Otherwise, please remove this section.**

### CODE REVIEW

**Comment by marcfiu** [comment]
While it is fine to handle here, it would be nicer if the linode api would handle empty lists in this case and set it to None automatically.

**Comment by lgarber-akamai** [comment]
/acctest tests=firewall_update sha=35f54c118edb767c90e22f8e9b0c95714e2e7eed

**Review by lgarber-akamai — APPROVED** [review]

**Comment by zliang-akamai** [comment]
> While it is fine to handle here, it would be nicer if the linode api would handle empty lists in this case and set it to None automatically.

@marcfiu Did you have a chance to notify the Linode API team about this issue?

**Review by zliang-akamai — APPROVED** [review]

**Review by lgarber-akamai — APPROVED** [review]

**Comment by lgarber-akamai** [comment]
/acctest tests=firewall_update sha=08be018c0881ae434ba21a200717006fa1c01d41

**Review by zliang-akamai — APPROVED** [review]

**Pull request merged**
