### PR TITLE
Upgrade db versions to supported versions

### PR DESCRIPTION
**Pull request by zliang-akamai**
## 📝 Description

DBaaS team removed some old database versions from the list after the maintenance, so we would need to upgrade the version number in our test, otherwise the test would fail.

## ✔️ How to Test

`make test`

### CODE REVIEW

**Review by ezilber-akamai — APPROVED** [review]
Looks good!

**Comment by zliang-akamai** [comment]
/acctest tests=postgresql_basic sha=e91cdb347e97581e56a2251927e75d05b66e5611

**Comment by zliang-akamai** [comment]
/acctest tests=postgresql_basic sha=535460020ed61f06633e81dc5c77e17cd2d25085

**Comment by zliang-akamai** [comment]
/acctest tests=mysql_basic sha=535460020ed61f06633e81dc5c77e17cd2d25085

**Comment by zliang-akamai** [comment]
/acctest tests=postgresql_complex sha=d335799485bcc93779c3ed4462f8539f60478f75

**Comment by zliang-akamai** [comment]
/acctest tests=mysql_complex sha=d335799485bcc93779c3ed4462f8539f60478f75

**Comment by zliang-akamai** [comment]
/acctest tests=mysql_complex sha=d335799485bcc93779c3ed4462f8539f60478f75

**Comment by zliang-akamai** [comment]
acctest stops working???

**Comment by zliang-akamai** [comment]
/acctest tests=mysql_basic sha=d335799485bcc93779c3ed4462f8539f60478f75

**Comment by zliang-akamai** [comment]
/acctest tests=postgresql_complex sha=d335799485bcc93779c3ed4462f8539f60478f75

**Comment by zliang-akamai** [comment]
/acctest tests=mysql_complex sha=d335799485bcc93779c3ed4462f8539f60478f75

**Review by lgarber-akamai — APPROVED** [review]

**Comment by lgarber-akamai** [comment]
Great work! In the future we may want to consider dynamically resolving versions like we do for [LKE clusters](https://github.com/linode/ansible_linode/blob/main/tests/integration/targets/lke_cluster_basic/tasks/main.yaml#L6).

**Comment by zliang-akamai** [comment]
> Great work! In the future we may want to consider dynamically resolving versions like we do for [LKE clusters](https://github.com/linode/ansible_linode/blob/main/tests/integration/targets/lke_cluster_basic/tasks/main.yaml#L6).

That's cool! Maybe we can create a ticket and backlog it?

**Pull request merged**
