### PR TITLE
PR workflow change

### PR DESCRIPTION
**Pull request by vshanthe**
## 📝 Description
Allow running all integration tests on PR
**What does this PR do and why is this change necessary?**
Allow running all integration tests on PR

## 📷 Preview

**If applicable, include a screenshot or code snippet of this change. Otherwise, please remove this section.**

### CODE REVIEW

**Comment by zliang-akamai** [comment]
Is it a GitHub issue or? It shows nothing was changed in this PR...
image

**Comment by ykim-1** [comment]
Seems like it is already merged to dev. Recommend to test the workflow changes in forked repo for next time to avoid breaking changes. Might be good to post a build running all the tests for this PR 👍

**Comment by vshanthe** [comment]
https://github.com/linode/ansible_linode/actions/runs/7657658249/job/20868862087#step:11:1462

**Review by ykim-1 — APPROVED** [review]

**Comment by zliang-akamai** [comment]
I think the change is already in `dev` and this PR is not necessary. You can try to pull the latest dev to develop other stuff on top of it.

**Pull request closed without merging**
