### PR TITLE
Ansible SSH Key Module

### PR DESCRIPTION
**Pull request by zliang-akamai**

### CODE REVIEW

**Comment by zliang-akamai** [comment]
/acctest sha= 0d68c4697aa0d701469056f9344af8f466033a2c tests=ssh_key

**Review by jriddle-linode — APPROVED** [review]
Looks good, small nitpick might be to remove some of the whitespace from `docs/modules/ssh_key.md`

**Comment by lgarber-akamai** [comment]
/acctest sha=08a58b7c01f4edf6ccd2371f14705a7def53eb35 tests=ssh_key

**Comment by lgarber-akamai** [comment]
/acctest sha=0aac43b0a23cdc71f011e33c1c6eb782d0b9a55b tests=ssh_key

**Comment by zliang-akamai** [comment]
> Looks good, small nitpick might be to remove some of the whitespace from `docs/modules/ssh_key.md`



> Looks good, small nitpick might be to remove some of the whitespace from `docs/modules/ssh_key.md`

Good point! Don't know why the generated doc has so many white spaces...

**Comment by lgarber-akamai** [comment]
> > Looks good, small nitpick might be to remove some of the whitespace from `docs/modules/ssh_key.md`
> 
> Good point! Don't know why the generated doc has so many white spaces...

Looks like `make gendocs` is producing a bunch of whitespace due to the control statements in the J2 template. I'll see if I can properly fix this in a PR 🙂

**Review by lgarber-akamai — APPROVED** [review]

**Pull request merged**
