### PR TITLE
ref: Drop local event poller; migrate to Python SDK event poller

### PR DESCRIPTION
**Pull request by lgarber-akamai**
## 📝 Description

This change drops the embedded event polling framework and migrates to the new Python SDK event polling framework.

## ✔️ How to Test

```
make test
```

### CODE REVIEW

**Comment by zliang-akamai** [comment]
GHA test runs:
https://github.com/linode/ansible_linode/actions/runs/5447628919
https://github.com/linode/ansible_linode/actions/runs/5447627395
https://github.com/linode/ansible_linode/actions/runs/5447624984
https://github.com/linode/ansible_linode/actions/runs/5447623730
https://github.com/linode/ansible_linode/actions/runs/5447621794
https://github.com/linode/ansible_linode/actions/runs/5447620239
https://github.com/linode/ansible_linode/actions/runs/5447616421

**Comment by zliang-akamai** [comment]
GHA test runs:
https://github.com/linode/ansible_linode/actions/runs/5448811371
https://github.com/linode/ansible_linode/actions/runs/5448809743
https://github.com/linode/ansible_linode/actions/runs/5448808464
https://github.com/linode/ansible_linode/actions/runs/5448807322
https://github.com/linode/ansible_linode/actions/runs/5448805941
https://github.com/linode/ansible_linode/actions/runs/5448804503
https://github.com/linode/ansible_linode/actions/runs/5448802385
https://github.com/linode/ansible_linode/actions/runs/5448800780
https://github.com/linode/ansible_linode/actions/runs/5448799863
https://github.com/linode/ansible_linode/actions/runs/5448796406
https://github.com/linode/ansible_linode/actions/runs/5448794887
https://github.com/linode/ansible_linode/actions/runs/5448793510

**Review by zliang-akamai — APPROVED** [review]
Good work! We now have a cleaner ansible repo :tada:

**Review by yec-akamai — APPROVED** [review]
Nice work!

**Pull request merged**
